version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
          WWWGROUP: '${WWWGROUP}'
    ports:
      - '${APP_PORT:-8080}:80'
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: laraveluser
      DB_PASSWORD: password

  db:
    image: mysql:5.7
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
